### ISSUE TITLE
Difference between built-in Currency field?

### ISSUE THREAD

**Issue by poxin13** [vyuldashev/nova-money-field#2]
https://nova.laravel.com/docs/1.0/resources/fields.html#field-types

```
Currency Field
The Currency field generates a Number field that is automatically displayed using PHP's money_format function.
```

**Comment by vyuldashev** [comment]
From the screenshot in readme you can see that Balance is formatted as money, also this library supports converting to and from minor units (that means you can store money in database in int).

Also, try different locales, the value will be supported accordingly.
