### ISSUE TITLE
rounding of value

### ISSUE THREAD

**Issue by Dontorpedo** [vyuldashev/nova-money-field#23]
Input like 

238,21 is rounded to 238 
and 238,51 is roundet to 239, how can i stop this?

thanks
D

**Comment by zek** [comment]
Hi @Dontorpedo,

Can you try v1.3.3. It must be fixed in latest release by  #21

**Comment by Dontorpedo** [comment]
tried, now 1.3.4, stil the same rounding issue

**Comment by vyuldashev** [comment]
Please, provide more information to reproduce the issue.

**Comment by Dontorpedo** [comment]
nova version 1.21
laravel 5.7.19

code in resource

`Money::make('Nettopreis', 'EUR', 'netto_price')`

on the resource edit page, i enter 238,21.. its rounded back to 238, and above 238,51 its rounded to 239.. 

instead of showing 238,xx

**Comment by vyuldashev** [comment]
I tried it, seems good to me.

**Comment by zek** [comment]
@Dontorpedo can you provide migration and model file?

**Comment by Dontorpedo** [comment]
this is my model..

´´´´
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Nova\Actions\Actionable;
use Laravel\Scout\Searchable;

class Objekte extends Model
{
    use SoftDeletes;
    use Actionable;
    use Searchable;

    protected $table = 'Objects';
	
	public static $group = "Tools";
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'street', 'zipcode', 'sort_order', 'tour_id', 'netto_price'
    ];

    public function kunde()
    {
        return $this->belongsTo('App\Kunde');
    }

    public function tour()
    {
        return $this->belongsTo('App\Tour');
    }

    public function InvoicePosition()
    {
        return $this->hasMany('App\InvoicePosition');
    }

    //Casts of the model dates
    protected $casts = [
        'service_started_on' => 'date',
        'service_end_on' => 'date',
        'last_invoice' => 'datetime',
    ];
}

´´´´


i dont have a migration file, db was imported from another project (not laravel)
