### ISSUE TITLE
Not Showing Input

### ISSUE THREAD

**Issue by wefixit-tech** [vyuldashev/nova-money-field#24]
Laravel 5.7.19
Nova: 1.2.1
Nova Money: 1.3
Windows 10

The input dont show up in the create, edit or show view, i try to figured out but i cant make it work.
it was working fine in older version of nova but when i update to the new version stop working.

the only message it trow is this: 

Cannot read property 'status' of undefined
 /vendor/nova/app.js

**Comment by vyuldashev** [comment]
Fixed in v1.3.4.
