### ISSUE TITLE
Not displaying en-ZA although locale is installed

### ISSUE THREAD

**Issue by eugenevdm** [vyuldashev/nova-money-field#28]
If I put in:

`Money::make('Amount')->locale('en-ZA'),`

it displays _US$537,50_, which is incorrect. I should be **R537.50**

I'm running Linux Mint on localhost and have a hosted CentOS server and in both instances I'm observing the same. To check if my localhost understands the locale I did this:

> user@hostname ~ $ locale
> LANG=en_ZA.UTF-8
> LANGUAGE=en_ZA:en
> LC_CTYPE="en_ZA.UTF-8"
> LC_NUMERIC="en_ZA.UTF-8"
> LC_TIME="en_ZA.UTF-8"
> LC_COLLATE="en_ZA.UTF-8"
> LC_MONETARY="en_ZA.UTF-8"
> LC_MESSAGES="en_ZA.UTF-8"
> LC_PAPER="en_ZA.UTF-8"
> LC_NAME="en_ZA.UTF-8"
> LC_ADDRESS="en_ZA.UTF-8"
> LC_TELEPHONE="en_ZA.UTF-8"
> LC_MEASUREMENT="en_ZA.UTF-8"
> LC_IDENTIFICATION="en_ZA.UTF-8"
> LC_ALL=
> 

The locale seems correct, I used this [link](https://docs.microsoft.com/en-us/windows-hardware/customize/mobile/mcsf/set-languages-and-locales) to check.

I don't know where else to start troubleshooting! Please assist and thank you so much for this wonderful needed addition to Nova.

**Comment by vyuldashev** [comment]
Try

`Money::make('Amount', 'ZAR')->locale('en-ZA'),`

**Comment by eugenevdm** [comment]
The worked!! Thank you so much :1st_place_medal:
