### ISSUE TITLE
Value shows with a "-" on detail page, when value is 0

### ISSUE THREAD

**Issue by julianpoma** [vyuldashev/nova-money-field#3]
Hi! First, thank you for the hard work! This package is really useful.

Just a minor and aesthetic thing I notices: when the field value is 0, on the details view it shows as a "-" (null) instead of showing $ 0,00. On the index view, it works great.

I am using minor units

Some pictures:

On index:

![image](https://user-images.githubusercontent.com/19490445/44694957-f6368180-aa46-11e8-8d2d-2d2f6340bfe8.png)

Detail
![image](https://user-images.githubusercontent.com/19490445/44694964-03ec0700-aa47-11e8-9580-a7d45399c5f7.png)

The DB entry
![image](https://user-images.githubusercontent.com/19490445/44694977-136b5000-aa47-11e8-8a0a-45b29c70ba24.png)

Thank you so much!

**Comment by vyuldashev** [comment]
Just tagged v1.0.2 which contains a fix for this issue.
