### ISSUE TITLE
Documentation update about how to add db_column_name?

### ISSUE THREAD

**Issue by shockingResident** [vyuldashev/nova-money-field#36]
Kindly update your documentation to elaborate one simple issue that majority faces.
How to set db_column_name?
It wasted couple of hour, and mental stress also. You should optimize your documentation.

**Comment by BinaryKitten** [comment]
HI @shockingResident, 

in this situation, do you mean setting the column name for the field or on the model?

Ultimately this field follows similar pattern to the other Fields out there for nova, with the parameters set.
this looks to the __construct of the field type to see how and what is, can be passed.

That being said, I have created a PR for you covering this update.
