### ISSUE TITLE
0 minor units not displayed

### ISSUE THREAD

**Issue by eberkund** [vyuldashev/nova-money-field#7]
If you set the value to something like 123.00 then go to edit your model again, it will be displayed as 123 instead of 123.00.

**Comment by vyuldashev** [comment]
@eberkund `composer update` and check, please.

**Comment by eberkund** [comment]
The view page is fixed (appears as 123.00_ however on the edit page it still appears without decimal places.

<img width="725" alt="screen shot 2018-09-12 at 11 18 41 am" src="https://user-images.githubusercontent.com/4555959/45434976-931b3080-b67d-11e8-9e7d-ce4681b217cb.png">

By the way I like the way the currency is also displayed now, nice touch!

**Comment by nickels** [comment]
Encountering the same 'issue', great package!

**Comment by vyuldashev** [comment]
Just tagged v1.1.0, check it please.
